# Generated by Django 4.2 on 2024-01-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog2',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
