# Generated by Django 5.0.1 on 2024-01-27 05:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods_api', '0002_blog1_author_blog2_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog1',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='boardminutes',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
