# Generated by Django 5.0.1 on 2024-01-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('neighborhoods_api', '0003_alter_blog1_content_alter_blog2_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog1',
            options={'verbose_name_plural': 'Blogs (Type 1)'},
        ),
        migrations.AlterModelOptions(
            name='blog1category',
            options={'verbose_name_plural': 'Blog (Type 1) Categories'},
        ),
        migrations.AlterModelOptions(
            name='blog2',
            options={'verbose_name_plural': 'Blogs (Type 2)'},
        ),
        migrations.AlterModelOptions(
            name='blog2category',
            options={'verbose_name_plural': 'Blog (Type 2) Categories'},
        ),
        migrations.AlterModelOptions(
            name='boardminutes',
            options={'verbose_name_plural': 'Board Minutes'},
        ),
        migrations.AddField(
            model_name='blog1',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog2',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='boardminutes',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('committee', models.ManyToManyField(to='neighborhoods_api.committee')),
            ],
        ),
    ]
