# Generated by Django 5.0.1 on 2024-01-27 17:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods_api', '0004_alter_blog1_options_alter_blog1category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog1',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardminutes',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
