# Generated by Django 5.0.1 on 2024-01-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods_api', '0005_alter_blog1_content_alter_blog2_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog1',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='blog2',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
